# add the following to _config.yml file
title: >
  PK
  Possakorn Kittipipatthanapong

logo: /assets/img/my_profile-circle.png
#description: text below image
show_downloads: true
theme: jekyll-theme-minimal
