# add the following to _config.yml file
title: >
  PK
  Possakorn Kittipipatthanapong

logo: /assets/img/my_profile-circle.png
#description: text below image
show_downloads: false
google_analytics: G-NM6L3XL7NV
theme: jekyll-theme-minimal
